server:
  port: 8080
spring:
  application:
    name: publications-service
  datasource:
    # para que coincida exactamente con tu docker-compose.yml
    url: jdbc:postgresql://db-publications:5432/db_publications
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

authors:
  service:
    # En código Java, el cliente ya le suma "/authors/" automáticamente.
    url: ${AUTHORS_SERVICE_URL}